version: 2

builds:
  - id: babybox-mock
    main: ./main.go
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
    binary: babybox-mock

archives:
  - id: default
    builds:
      - babybox-mock
    format: tar.gz
    name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}"

checksum:
  name_template: "checksums.txt"

release:
  github:
    owner: zbyju
    name: babybox-mock
