version: 2

builds:
  - id: babybox-mock
    main: ./main.go
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
    binary: babybox-mock

    hooks:
      pre:
        - npm install --prefix frontend
        - npm run build --prefix frontend
        - wails build

    skip: true

archives:
  - id: default
    files:
      - build/bin/babybox-mock
    name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}"

checksum:
  name_template: "checksums.txt"

release:
  github:
    owner: zbyju
    name: babybox-mock
