version: "3.8"

services:
  backend:
    build:
      context: ./docker/prod/backend
    ports:
      - "3000:3000"

  frontend:
    build:
      context: ./docker/prod/frontend
    ports:
      - "80:80"
