name: Build and Release

on:
  release:
    types: [published]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        build:
          - { name: babybox-mock, platform: windows/amd64, os: windows-latest }
          - { name: babybox-mock, platform: linux/amd64, os: ubuntu-latest }
          - { name: babybox-mock, platform: darwin/arm64, os: macos-latest }

    runs-on: ${{ matrix.build.os }}

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - uses: dAppServer/wails-build-action@main
        with:
          build-name: ${{ matrix.build.name }}
          build-platform: ${{ matrix.build.platform }}
          wails-version: "v2.9.0"
          go-version: "1.21"
          node-version: "18.x"
          nsis: true
